sudo: required
services:
  - docker

before_install:
  - docker build -t ctnkyrd/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ctnkyrd/react-test npm test -- --coverage

after_success:
  - docker build -t ctnkyrd/multi-client ./client
  - docker build -t ctnkyrd/multi-nginx ./nginx
  - docker build -t ctnkyrd/multi-server ./server
  - docker build -t ctnkyrd/multi-worker ./worker
  #Log in to the docker CLI
  
  #take those images and push them to docker-hub